# Configurações do Servidor
server.port=${PORT:8080}

# Database Configuration - Usando variáveis de ambiente para produção
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/meu_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Segurança - JWT Secret (Exemplo)
api.security.token.secret=${JWT_SECRET:my-secret-key-123}