# Configurações do Servidor
server.port=${PORT:8080}

# Database Configuration - Aiven MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://heindex-mayconmnzes-6dd6.c.aivencloud.com:24620/defaultdb?ssl-mode=REQUIRED&useSSL=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_IgBwsmDY6fPjnFmoW1B}

# Forçar Driver e Dialeto MySQL (Isso resolve o erro do log)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configurações de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Credenciais Cloudinary
cloudinary.cloud_name=${CLOUDINARY_NAME:dkreomuo2}
cloudinary.api_key=${CLOUDINARY_KEY:498376488395782}
cloudinary.api_secret=${CLOUDINARY_SECRET:NZ1_93_649Re9Dftb35fpRdN35U}

# Upload de Arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Monitoramento (Actuator)
management.endpoints.web.exposure.include=health
